# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50e201efe375cfd211b7455265de8fefd5268fdca0de3358f776993cec1a8aeda45345e972867a994b1c63942eb98ec6d5a2bd828bd0e3df7e6863d0cc9c8b1e

test:
  secret_key_base: c0ca20f2d43cd46ea056199492e9ba03da8915400825da02b8bee03475a769ced21c95c69d99a7e321e99202a4288e0cc693e5fcebe05dd5a1c614edf714f739

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
